name: LinkArchive GitHub Action 
run-name: Running
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    
env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: linkarchive
  AWS_CODE_DEPLOY_APPLICATION: LinkArchive-CD
  AWS_CODE_DEPLOY_GROUP: LinkArchive-CD-group

jobs:
  build-with-gradle:
    runs-on: ubuntu-20.04
    steps:
    - name: dev 브랜치로 이동
      uses: actions/checkout@v3
      with:
        ref: dev
    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: gradlew에 실행 권한 부여
      run: chmod +x ./gradlew
    - name: 프로젝트 빌드
      run: ./gradlew clean build
